apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: canarydeck-flagger
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canarydeck-flagger

  service:
    port: 80
    targetPort: 3000

  analysis:
    interval: 60s
    threshold: 5
    stepWeight: 20
    maxWeight: 100

    metrics:
      - name: canarydeck-success-rate
        templateRef:
          name: canarydeck-success-rate
        thresholdRange:
          min: 95
        interval: 1m

      - name: canarydeck-request-duration
        templateRef:
          name: canarydeck-request-duration
        thresholdRange:
          max: 500
        interval: 1m

